<template lang="pug">
MButton(
  v-bind="$attrs"
  :disabled-tooltip="triggerButtonDisabledTooltip"
  :permission="permission"
  :size="triggerButtonSize"
  :variant="variant"
  @click="modalRef?.open"
  :data-testid="dataTestid ? dataTestid + '-button' : undefined"
  )
  template(#icon)
    <!-- @slot Optional: Icon for the trigger button. -->
    slot(name="trigger-button-icon")

  | {{ triggerButtonLabel }}

MActionModal(
  ref="modalRef"
  :title="modalTitle"
  :action="action"
  :ok-button-label="okButtonLabel"
  :ok-button-disabled-tooltip="okButtonDisabledTooltip"
  :disable-safety-lock="disableSafetyLock"
  :modal-size="modalSize"
  :variant="variant"
  @show="emit('show')"
  @hide="emit('hide')"
  @ok="emit('ok')"
  @cancel="emit('cancel')"
  :data-testid="dataTestid ? dataTestid + '-modal' : undefined"
  )
  template(
    v-if="$slots['modal-subtitle']"
    #modal-subtitle
    )
    <!-- @slot Optional: Sub-title for the modal. -->
    slot(name="modal-subtitle")

  template(#default)
    <!-- @slot Default: Main content area for the modal body (HTML/components supported). -->
    slot

  template(
    v-if="$slots['right-panel']"
    #right-panel
    )
    <!-- @slot Optional: Right-side content for a two-column modal (HTML/components supported). -->
    slot(name="right-panel")

  template(
    v-if="$slots['bottom-panel']"
    #bottom-panel
    )
    <!-- @slot Optional: Additional content for a three-column modal (HTML/components supported). -->
    slot(name="bottom-panel")

  template(
    v-if="$slots['result-panel']"
    #result-panel
    )
    <!-- @slot Optional: Content shown after a successful action (HTML/components supported). -->
    slot(name="result-panel")

  template(
    v-if="$slots['ok-button-icon']"
    #ok-button-icon
    )
    <!-- @slot Optional: Icon for the OK button (HTML/components supported). -->
    slot(name="ok-button-icon")
</template>

<script setup lang="ts">
import { ref } from 'vue'

import MButton, { type ButtonSize } from '../primitives/MButton.vue'
import type { Variant } from '../utils/types'
import MActionModal from './MActionModal.vue'

export interface Props {
  /**
   * Optional: Title for the modal. Has more room than the button to describe this action.
   * @example 'Update Broadcast Details'
   */
  modalTitle: string
  /**
   * Function to execute when the ok-button has been pressed. Async functions show a loading spinner.
   * @example
   * async function doSomething {
   *  await gameServerApi.post('/someRoute', someData) // Await a request
   *  showSuccessNotification('Did a thing!') // Show visual feedback
   * someSubscription.triggerRefresh() // Force an immediate data refresh
   * }
   */
  action: () => Promise<void>
  /**
   * Optional: Text label for the trigger button. Should be kept as short as possible.
   * @example 'Update'
   */
  triggerButtonLabel: string
  /**
   * Optional: Whether to disable the trigger button.
   * Set this prop to  a `string` to disable the trigger button and show a tooltip.
   * @example 'Cancel this scan job.'
   */
  triggerButtonDisabledTooltip?: string
  /**
   * Optional: Set the size of the trigger button. Defaults to 'default'.
   * @example 'small'
   */
  triggerButtonSize?: ButtonSize
  /**
   * Optional: Select a custom color variant for the trigger button. Defaults to 'primary'.
   * @example 'warning'
   */
  variant?: Variant
  /**
   * Optional: A custom label for the pop-over modal's ok-button. Defaults to 'Ok'.
   * @example 'Update'
   */
  okButtonLabel?: string
  /**
   * Optional: Disable the ok-button and show a tooltip.
   * @example 'Please fill out all required fields.' // Disables the ok-button and shows a tooltip.
   */
  okButtonDisabledTooltip?: string
  /**
   * Optional: Remove the safety lock from the OK button.
   */
  disableSafetyLock?: boolean
  /**
   * Optional: Set a custom size for the modal. Defaults to 'default'.
   * @example 'large'
   */
  modalSize?: 'default' | 'large'
  /**
   * Optional: Set a permission requirement for being able to use this action.
   * @example 'api.broadcasts.edit'
   */
  permission?: string
  /**
   * Optional: Unique ID for this action that is used to generate data-testids for the button and modal.
   * This is useful for testing, as it allows you to easily find the component and related children in the DOM.
   * Note: Child element test ids are generated by appending '-button' or '-modal' to the testId.
   * @example 'update-broadcast' Child component test ids: 'update-broadcast-button' and 'update-broadcast-modal'
   */
  dataTestid?: string
  /**
   * Optional: Whether to disable the trigger button.
   * Set this prop to `true` to disable the trigger button or use a `string` to disable the trigger button and show a tooltip.
   * @example true // Disables the trigger button.
   * @example 'Cancel this scan job.' // Disables the trigger button and shows a tooltip.
   * @deprecated This prop was removed in Release 30. Use `triggerButtonDisabledTooltip` instead.
   */
  triggerButtonDisabled?: never
  /**
   * Optional: Disable the 'Ok' button. Good for form validation.
   * Set this prop to `true` to disable the ok-button or use a `string` to disable it and display a tooltip.
   * @example true // Disables the ok-button.
   * @deprecated This prop was removed in Release 31. Use `okButtonDisabledTooltip` instead.
   */
  okButtonDisabled?: never
}

const props = withDefaults(defineProps<Props>(), {
  triggerButtonDisabledTooltip: undefined,
  triggerButtonSize: 'default',
  variant: 'primary',
  okButtonLabel: 'Ok',
  okButtonDisabledTooltip: undefined,
  okButtonDisabled: undefined,
  disableSafetyLock: undefined,
  modalSize: undefined,
  permission: undefined,
  dataTestid: undefined,
  triggerButtonDisabled: undefined,
})

const modalRef = ref<typeof MActionModal>()

const emit = defineEmits(['ok', 'cancel', 'show', 'hide'])
</script>
