<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <RootNamespace>Game.Cloud</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(SharedCodePath)\**\*.cs" LinkBase="SharedCode" />
    <Compile Update="..\..\Assets\SharedCode\TypeCodes\MessageCodes.cs">
      <LinkBase>SharedCode\</LinkBase>
      <Link>SharedCode\TypeCodes\MessageCodes.cs</Link>
    </Compile>
    <Compile Update="..\..\Assets\SharedCode\Leaderboard\LeaderboardDto.cs">
      <Link>SharedCode\Leaderboard\LeaderboardDto.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(MetaplayServerPath)\Cloud\Metaplay.Cloud.csproj" />
    <ProjectReference Include="$(MetaplayServerPath)\CodeAnalyzers\Metaplay.CodeAnalyzers.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
    <ProjectReference Include="$(MetaplayServerPath)\CodeAnalyzers.Shared\Metaplay.CodeAnalyzers.Shared.csproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <OutputItemType>Analyzer</OutputItemType>
    </ProjectReference>
  </ItemGroup>
</Project>
